### ISSUE TITLE
ninja build

### ISSUE THREAD

**Issue by SoahCeruP** [gsauthof/libxfsx#2]
while running the ninja command i get this error 

* "‘assert’ is defined in header"

**Comment by gsauthof** [comment]
Ok, I can reproduce this on Fedora 35, the actual error GCC reports there is:

```
libxfsx/xfsx/xfsx.cc:747:5: error: ‘assert’ was not declared in this scope
```
Looks like some system headers removed some accidental implicit assert.h availability.

I've fixed it and another issue in the master branch.

FWIW, when compiling on Fedora 35, I noticed that the old sol2 version (referenced via a submodule) doesn't work anymore with current lua headers.

Thus, I had to compile with `cmake -G Ninja .. -DXFSX_USE_LUA=off` to work around this.

If one needs Lua support, one has to upgrade the sol2 dependency. Either to the current sol2 version 3 (which might require some changes in libsfx) or some newer release from the version 2 branch (in case that is still maintained).
