### ISSUE TITLE
Build issues for OSX M1 and Ubuntu 20

### ISSUE THREAD

**Issue by fuzemobi** [gsauthof/libxfsx#3]
I'm having issues building on both M1 Mac OS Ventura 23.3.1 and Ubuntu 20.   It seems the build instructions are incomplete and there are many issues when attempting a build.   Is it possible to update your Readme.md to include specific build instructions?

Here is a detailed example of what I am seeing:

Development % git clone https://github.com/gsauthof/libxfsx.git
Cloning into 'libxfsx'...
remote: Enumerating objects: 2223, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 2223 (delta 0), reused 1 (delta 0), pack-reused 2219
Receiving objects: 100% (2223/2223), 1.70 MiB | 6.37 MiB/s, done.
Resolving deltas: 100% (1448/1448), done.
Development % cd libxfsx
libxfsx % mkdir build
libxfsx % cd build
build % cmake ..
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test XFSX_HAVE_FROM_CHARS
-- Performing Test XFSX_HAVE_FROM_CHARS - Failed
CMake Error at CMakeLists.txt:18 (include):
  include could not find requested file:
    /Development/libxfsx/cmake/modules/coverage.cmake
CMake Error at CMakeLists.txt:19 (include):
  include could not find requested file:
    /Development/libxfsx/cmake/modules/sanitize.cmake
-- Found Boost: /opt/homebrew/lib/cmake/Boost-1.81.0/BoostConfig.cmake (found suitable version "1.81.0", minimum required is "1.58") found components: system filesystem regex unit_test_framework
CMake Error at CMakeLists.txt:72 (add_subdirectory):
  The source directory
    /Development/libxfsx/libixxx
  does not contain a CMakeLists.txt file.
CMake Error at CMakeLists.txt:73 (add_subdirectory):
  The source directory
    /Development/libxfsx/libixxxutil
  does not contain a CMakeLists.txt file.
CMake Error at CMakeLists.txt:74 (add_subdirectory):
  The source directory
    /Development/libxfsx/libxxxml
  does not contain a CMakeLists.txt file.
CMake Error at CMakeLists.txt:75 (add_subdirectory):
  The source directory
    /Development/libxfsx/libgrammar
  does not contain a CMakeLists.txt file.
CMake Error at CMakeLists.txt:78 (add_subdirectory):
  The source directory
    /Development/libxfsx/fmt
  does not contain a CMakeLists.txt file.
CMAKE_SYSTEM_PREFIX_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.26.0;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local
CMAKE_PREFIX_PATH:
LUA_LIB: /opt/homebrew/lib/liblua.dylib
LUA_INCLUDE_DIR: /opt/homebrew/include/lua
LUAXX_INCLUDE_DIR: /opt/homebrew/include/lua
-- Configuring incomplete, errors occurred!

I have also tried Xcode:
build % cmake ../CMakeLists.txt -G Xcode ..
This results in the same errors as above +

CMAKE_SYSTEM_PREFIX_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.26.0;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local
CMAKE_PREFIX_PATH:
LUA_LIB: /opt/homebrew/lib/liblua.dylib
LUA_INCLUDE_DIR: /opt/homebrew/include/lua
LUAXX_INCLUDE_DIR: /opt/homebrew/include/lua
-- Configuring incomplete, errors occurred!

I have similar issues on Ubuntu20.

I would be happy to provide more details and logs.    I would also be happy to test with docker as you have in your travis.yml but I have not been successful testing that either.

**Comment by gsauthof** [comment]
The steps for cloning the submodules weren't accurate. I've updated the README.

On Fedora 37 I have to disable Lua support because apparently there were some backwards-incompatible changes in the Lua headers. Shouldn't be too hard to fix, though. (i.e. also by updating the sol2 depedency to some more recent stable release)

This just succeeded on Fedora 37:

```
git clone https://github.com/gsauthof/libxfsx.git
cd libxfsx
git submodule update --init
mkdir build
cd build
cmake .. -DXFSX_USE_LUA=off
make bed
```

**Comment by fuzemobi** [comment]
This worked perfectly!  I now have both Ubuntu 18x/20x/22x and OSX Ventura M1 working.

Thanks!
